use_frameworks!

target 'UIKitExpansion_Example' do
  pod 'UIKitExpansion', :path => '../'

  target 'UIKitExpansion_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
